### PR TITLE
Added cancellation token overloads to BeginReceiveMessages.

### PR DESCRIPTION
**Pull request by pvginkel**
Implements support for cancellation tokens on `BeginReceiveMessage`. This implementation is done by mimicking the behavior of timer expiration. When the cancellation token is cancelled, and we had a timer, this is stopped.

Implemented to support the Microsoft.Azure.ServiceBus library and submitted https://github.com/Azure/azure-sdk-for-net/pull/7393 for that.

Branched off of 2.4.2 because that's where Microsoft.Azure.ServiceBus is at and there are some breaking changes in master.

Closes https://github.com/Azure/azure-service-bus-dotnet/issues/258 and others.

### CODE REVIEW

**Comment by pvginkel** [comment]
This specifically is to be able to do a clean shutdown. The problem is that Azure Service Bus uses lock tokens, and that the receiver tracks those and only allows lock tokens to be abandoned on the receiver that received the associated message. With this change, I can change the shutdown procedure to work as follows:

* Prepare a task completion source;
* Raise the cancellation token to have the receive stop;
* After the receiver stops, set the result of the task completion source;
* This allows me to then await that task completion source in the shutdown process. When this fires, any messages that were still outstanding can be abandoned;
* Only then close the receiver.

The point is that if I trigger cancelling the message receive by closing the receiver, I am not able anymore to abandon any outstanding lock tokens, having to depend on the lock timeout to make them available again. https://github.com/Azure/azure-sdk-for-net/pull/7393 contains a more thorough explanation from the perspective of the Azure Service Bus implementation. I've tried limiting my changes to the Azure Service Bus code, but then this becomes a problem: https://github.com/Azure/azure-amqp/blob/master/src/ReceivingAmqpLink.cs#L636. When cancelling the outstanding receives, completion is put onto the thread pool. Because of that, there's no way to synchronize this with the shutdown process, even if we'd limit the changes to the Azure Service Bus library. So, instead of trying to hack something in there, I'd thought it better to solve the root cause of the issue i.e. not being able to cancel an outstanding receive.

**Comment by pvginkel** [comment]
I understand this. I am aware how the AMQP protocol should work. The product I'm implementing Azure Service Bus for supports RabbitMQ, and we're not seeing these issues.

As for the Azure Service Bus limitations, I'm aware. We've contacted the Azure Service Bus team and they did confirm this. My own tests were showing the same. I've just done a test with the following code change to the Azure Service Bus library:

```cs
var amqpLinkSettings = new AmqpLinkSettings
{
    Role = true,
    TotalLinkCredit = (uint)this.PrefetchCount,
    AutoSendFlow = this.PrefetchCount > 0,
    Source = new Source { Address = this.Path, FilterSet = filterMap /* --> */ , DefaultOutcome = AmqpConstants.ReleasedOutcome /* <-- */ },
    SettleType = (this.ReceiveMode == ReceiveMode.PeekLock) ? SettleMode.SettleOnDispose : SettleMode.SettleOnSend
};
```

This shows the same behavior as just closing the receiver link: the messages are locked until the lock timeout expires.

I understand that this is a limitation of Azure Service Bus. I'm not stating the AMQP library is implementing the protocol wrong, I know this is all correct. I'm saying that Azure Service Bus is breaking the contract. I understand that this is not ideal, but chances are slim this is going to be fixed at the Azure Service Bus server side anytime soon. I'm also not suggesting this library should break the protocol implementation to accommodate the limitations of Azure Service Bus. From the code, I could see that the timeout already implemented what I needed to get cancellation tokens implemented properly; we just need a different path into this code path. From the perspective of the AMQP library, this is implemented as an timer event that just wasn't raised by the timer but through a different mechanism.

**Comment by brandondahler** [comment]
After looking at the issue I agree with @xinchen10's  position that it is not generally a AMPQ problem more than a ServiceBus implementation problem; however, I think that the general request @pvginkel has good merit from an API standpoint.

I'd suggest that we unify the `TimeSpan timeout` and `CancellationToken cancellationToken` parameters into a single `CancellationToken cancellationToken` parameter.  We can preserve the old TimeSpan timeout overloads by calling:
```
...
{
    var cancellationTokenSource = new CancellationTokenSource(timeout)
    return BeginReceiveMessage(cancellationTokenSource.Token, ...)
}
```

This adds flexibility for the user to better define cancellation patterns in whatever ways they want, while still keeping backwards compatibility with existing the timeout overloads.

**Comment by pvginkel** [comment]
@brandondahler this seems to make sense. However, that would be a more invasive change. I'm happy to make an attempt at the changes, but I think we'd need some agreement on the implementation approach before I'd make an attempt.

@xinchen10 what do you think would be the best next step?

**Comment by danielmarbach** [comment]
@brandondahler that would work but you definitely want to dispose the token source that timeout due to them being associated with timers.

**Comment by brandondahler** [comment]
@danielmarbach you’re correct, we’d actually need to make sure that the CTS was disposed on EndReceiveMessage in case the timeout value was arbitrarily large. 

CTS automatically takes care of disposing the timer once the timer does fire, but you could have a large amount of timers that do nothing if you make the timeout long and call that method a bunch of times. 

Good call out.

**Comment by xinchen10** [comment]
Thank you very much for submitting the PR but we have to close it for now. 1. AMQP supports the graceful shutdown of a receiver by specifying the default outcome of the link endpoint. Closing a link should apply the outcome to all outstanding deliveries. I'd suggest contact the Service Bus team to enable that in SDK or add the support on the service side. This is going to benefit all other AMQP clients that have the same requirement. 2. It introduces inconsistency in Task based APIs. There is no plan to add CancellationToken support in all Task based APIs at this moment.

**Comment by JoshLove-msft** [comment]
Going to try to revive this and see if this approach will work with the new T2 libraries. /cc @danielmarbach

**Comment by pvginkel** [comment]
Wow, that would be great. We're still on a custom version of the ASB libraries because we do need this functionality. What though are the T2 libraries?

**Comment by danielmarbach** [comment]
@pvginkel The new client SDK https://www.nuget.org/packages/Azure.Messaging.ServiceBus

**Pull request closed without merging**
