### PR TITLE
Dispose CancellationTokenSource in Singleton OpenAsync with a timeout

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by aarondandy** [comment]
@xinchen10, what is the preferred way to get a fix like this on both the v2 and v3 branches?

**Comment by danielmarbach** [comment]
The test that failed worked locally. It also seems that the build script swallows the exit code in some cases. I'm happy to send in another PR after the other two that bumps some refs are merged

**Review by xinchen10 — APPROVED** [review]

**Comment by danielmarbach** [comment]
@xinchen10 any reasons why this was not brought to the hotfix branch and released?

**Comment by xinchen10** [comment]
Hi @danielmarbach, this issue does not exist in hotfix branch where timeout is handled differently.

**Pull request merged**
